apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-inference
  template:
    metadata:
      labels:
        app: ai-inference
    spec:
      containers:
      - name: ai-service
        image: <AWS_ECR_IMAGE>
        ports:
        - containerPort: 8000
